version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    expose :
      - 5672
      - 15672

    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
      - "15671:15671"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 15

  flask-api:
    build:
      context: .
      dockerfile: DockerfileFlask
    ports:
      - "5000:5000"

    depends_on:
      - rabbitmq


  nginx:
    image: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask-api

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data

volumes:
  minio-data:

