version: '3'

services:
  rabbitmq: 
    image: rabbitmq:management
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 15

    env_file:
      - ../env


  flask-api:
    build:
      context: .
      dockerfile: DockerfileFlask

    ports:
      - "5000:5000"

    env_file:
      - ../env

    depends_on:
      - rabbitmq

  nginx:
    image: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask-api
